const ACCESS_TOKEN_SECRET = "accesstoken";
const REFRESH_TOKEN_SECRET = "refreshtoken";
const ACCESSTOKEEXPIRETIME = "24h";
const REFRESHTOKEEXPIRETIME = "24h";

module.exports = {
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  ACCESSTOKEEXPIRETIME,
  REFRESHTOKEEXPIRETIME,
};
